config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.role == 'admin' } do
      mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users

  get '403', to: 'errors#forbidden', as: 'forbidden'
  get '404', to: 'errors#not_found', as: 'not_found'
  get '422', to: 'errors#unprocessable_entity'
  get '500', to: 'errors#internal_server_error'

  root to: "geo_refs#index"

  get 'profile', to: 'profile#show'
  patch 'profile', to: 'profile#update'
  get 'profile/password', to: 'profile#password'
  patch 'profile/password', to: 'profile#update_password'

  resources :search, only: %i[index]
  resources :photos, only: %i[index show edit update destroy]
  resources :topos
  resources :zones, only: %i[index]
  resources :regulations, only: %i[index show edit update destroy] do
    resources :regulated_geo_refs, only: %i[new create]
  end
  resources :regulated_geo_refs, only: %i[edit update destroy]
  resources :routes, shallow: true do
    collection do
      get 'autocomplete'
    end
    resources :ascents, only: [:index, :new]
    resources :ticklists, only: [:index, :new]
    resources :photos, only: %i[index new create]
    resources :comments, only: %i[index new create]
  end

  resources :closures do
    member do
      post 'add_geo_ref'
      post 'remove_geo_ref'
    end
    resources :season_closures, only: %i[new create]
  end
  resources :season_closures, only: %i[edit update destroy]

  resources :ascents, only: %i[index show]
  resources :ticklists, only: %i[index show]

  resources :users, only: %i[show index] do
    resources :ascents, except: :show
    resources :ticklists, except: :show
    resources :photos, only: [:index]
  end

  resources :first_ascent_people do
    collection do
      get 'autocomplete'
    end
  end
  get 'scales/:scope', to: 'scales#table', defaults: { scope: 'climbing' }

  resources :geo_refs, except: :new  do
    collection do
      get(
        'new/:type',
        to: 'geo_refs#new',
        constraints: { type: /(Country|Region|Crag|Sector|Parking)/ },
        as: 'new'
      )
      get 'browse'
      get 'autocomplete'
      get 'map'
    end

    member do
      get 'map_items'
      get :sort_routes
      put :reorder_routes
      get :sort_childs
      put :reorder_childs
      get :select_items
      patch :move_items
    end
    resources :ascents, only: [:index]
    resources :ticklists, only: [:index]
    resources :approaches, only: [:index]
    resources :photos, only: %i[index new create]
    resources :topos
    resources :secondary_zones, only: %i[new create edit update destroy]
    resources :comments, only: %i[index new create]
    resources :paths, only: %i[index new create]
    resources :permissions, only: %i[index create edit update destroy]
    resources :regulations, only: %i[index new create]
  end

  resources :grades, only: [] do
    collection do
      get 'autocomplete'
    end
  end

  resources :styles, only: [] do
    collection do
      get 'autocomplete'
    end
  end

  resources :comments, only: %i[index edit update destroy]

  resources :paths, only: %i[index show edit update destroy] do
    member do
      post 'add_geo_ref'
      post 'remove_geo_ref'
      get 'map_items'
    end
  end

  get 'help', to: redirect('/help/README.html'), as: nil
  get 'help/*path', to: 'help#show', as: 'help'
  
  namespace :admin do
    root to: 'dashboard#dashboard'
    get '/monitoring', to: 'monitoring#index'
    get '/sys_info', to: 'sys_info#index'
    get '/background_jobs', to: 'background_jobs#index'
    resources :users do
      collection do
        get :members
        get :contributors
        get :admins
        get 'autocomplete'
      end
    end
  end

  get 'custom_layout', format: :css, to: 'custom_layout#index', as: :custom_layout

  get 'password_strength', to: 'password_strength#check'

  get '/abilities/:id', to: 'abilities#show'

  health_check_routes
end

app/models/geo_ref.rb
class GeoRef < ApplicationRecord
  class << self
    def geo_ref_types
      %w[Country Region Crag Sector Parking].freeze
    end

    def icon
      'map-marker'
    end

    def valid_parent_classes
      []
    end

    def valid_parent_class?(klass)
      valid_parent_classes.include?(klass)
    end
  end

  has_many :childs, class_name: "GeoRef", foreign_key: "parent_id", dependent: :nullify
  belongs_to :parent, class_name: "GeoRef", optional: true
  belongs_to :zone, optional: true
  has_many :secondary_zones, dependent: :destroy
  has_many :regulations, dependent: :destroy
  has_many :regulated_geo_refs, dependent: :destroy
  belongs_to :closure, optional: true
  has_many :routes, dependent: :destroy
  has_many :photos, as: :target, dependent: :destroy
  has_many :topos, as: :target, dependent: :destroy
  has_many :comments, as: :target, dependent: :destroy
  has_many :paths, dependent: :destroy
  has_and_belongs_to_many :approaches, class_name: 'Path'

  validates_presence_of :name

  validates(
    :orientation,
    numericality: {
      allow_nil: true,
      less_than: 361
    },
    if: :supports_orientation?
  )
  validates :orientation, absence: true, unless: :supports_orientation?

  validates(
    :height,
    numericality: {
      allow_nil: true,
      less_than: 5000
    },
    if: :supports_height?
  )
  validates :height, absence: true, unless: :supports_height?

  validates :zone, absence: true, unless: :supports_zone?
  validates :secondary_zones, absence: true, unless: :supports_zone?

  validates :access, presence: true, access_level: true

  validates(
    :type,
    inclusion: {
      in: GeoRef.geo_ref_types,
      message: '%{value} is not a valid GeoRef type!'
    }
  )

  validate :validate_parent_type
  def validate_parent_type
    return if parent.nil? && is_a?(Country) 
    
    if parent.nil?
      errors.add(:parent, _('cannot be empty for type %{type}') % { type: self.class.name } )
      return
    end

    unless self.class.valid_parent_class?(parent.class)
      errors.add(
        :parent,
        _('must be of one of the following type: %{types}') % {
          types: self.class.valid_parent_classes.join(', ')
        }
      )
    end
  end
  attr_accessor :skip_parent_changed_validation
  validate :validate_parent_changed, unless: :skip_parent_changed_validation
  def validate_parent_changed
    if parent_id_changed? && self.persisted?
      errors.add(:parent, "cannot be changed")
    end
  end

  include PermissionAssignable
  include Taggable

  scope :with_location, -> { where.not(lat: nil).where.not(lng: nil) }

  def ransackable_attributes(auth_object = nil)
    %w[name type description height orientation]
  end

  def ransackable_associations(auth_object = nil)
    %w[zone routes tags]
  end

  def self.ransackable_scopes(auth_object = nil)
    %i[search_full_text]
  end

  include PgSearch::Model
  pg_search_scope(
    :search_full_text,
    against: {
      name:   'A',
      description: 'B',
      body: 'C'
    },
    using: {
      tsearch: {
        prefix: true,
        dictionary: 'simple'
      }
    }
  )

  def supports_orientation?
    false
  end

  def supports_height?
    false
  end

  def supports_zone?
    false
  end

  def supports_ascents?
    Routenbuch.features.ascents?
  end

  def supports_ticklists?
    Routenbuch.features.ticklists?
  end

  def supports_paths?
    false
  end

  def supports_approaches?
    false
  end

  def supports_regulations?
    Regulation.valid_geo_ref_type? self.class
  end

  def update_stats
    self.stats = {
      route_grade_stats: self.route_grade_stats,
      descendent_routes_count: self.descendent_routes.count,
      descendent_crags_count: self.descendent_crags.count,
      descendents_count: self.descendents.count,
      childs_count: self.childs.count,
    }
  end

  def route_grade_stats
    descendent_routes.joins(:grade)
      .group('grades.category')
      .order('MAX(grades.difficulty)')
      .count
  end

  def location?
    self.lat.present? and self.lng.present?
  end
  alias :latlng? :location?

  def location
    return unless latlng?

    Geokit::LatLng.new(lat,lng)
  end

  # search parents for closest location
  def next_location
    cur = self
    loop do
      break if cur.nil?
      return cur.location if cur.location.present?

      cur = cur.parent
    end

    return
  end

  def parents
    parents = []
    cur = self.parent
    while ! cur.nil? do
      parents += [ cur ]
      cur = cur.parent
    end
    parents
  end

  def descendents
    self_and_descendents - [self]
  end

  def self_and_descendents
    GeoRef.tree_for(self)
  end

  def ascents
    Ascent \
      .joins(:route) \
      .where('routes.geo_ref_id': self_and_descendents)
  end

  def ticklists
    Ticklist \
      .joins(:route) \
      .where('routes.geo_ref_id': self_and_descendents)
  end

  def descendent_routes
    subtree = GeoRef.tree_sql_for(self)
    Route.where("geo_ref_id IN (#{subtree})")
  end

  def descendent_crags
    self_and_descendents
      .where(type: 'Crag') - [self]
  end

  def self.tree_for(instance)
    where("#{table_name}.id IN (#{tree_sql_for(instance)})").order("#{table_name}.id")
  end

  def self.tree_sql_for(instance)
    <<-SQL
      WITH RECURSIVE search_tree(id, path) AS (
          SELECT id, ARRAY[id]
          FROM #{table_name}
          WHERE id = #{instance.id}
        UNION ALL
          SELECT #{table_name}.id, path || #{table_name}.id
          FROM search_tree
          JOIN #{table_name} ON #{table_name}.parent_id = search_tree.id
          WHERE NOT #{table_name}.id = ANY(path)
      )
      SELECT id FROM search_tree ORDER BY path
    SQL
  end

  # geokit
  acts_as_mappable :default_units => :kms

  def update_self_and_parents_stats
    GeoRefUpdateStatsJob.perform_later(id)
  end
end

app/controllers/geo_refs_controller.rb
class GeoRefsController < ApplicationController
  before_action(
    :set_geo_ref,
    only: %i[
      show edit update destroy
      map_items
      sort_routes reorder_routes
      sort_childs reorder_childs
      select_items move_items
    ]
  )
  before_action :set_move_items_params, only: %i[select_items move_items]
  skip_authorization_check only: %i[index browse autocomplete]

  def autocomplete
    @geo_refs = GeoRef \
      .where('name ILIKE (?)', "%#{params[:term]}%") \
      .accessible_by(current_ability, :read) \
      .limit(10)
    render(
      json: @geo_refs.map do |g|
        {
          id: g.id,
          value: g.name,
          label: "#{g.name} (#{g.class.name})",
        }
      end
    )
  end

  def map
    # TODO select items based on map (geokit)
  end

  def map_items
    authorize! :read, @geo_ref
    @childs = @geo_ref.childs.with_location.accessible_by(current_ability, :read)

    @items = if @childs.any?
               @childs
             else
               [@geo_ref]
             end

    render json: GeoRef::MapItemSerializer.new(@items).serializable_hash.to_json
  end

  def browse
    @geo_refs = GeoRef.where(parent: nil).accessible_by(current_ability, :read)
    respond_to do |format|
      format.html 
    end
  end

  def index
    @q = GeoRef.ransack(params[:q])
    @geo_refs = @q.result \
      .accessible_by(current_ability, :read)\
      .order(created_at: :desc) \
      .page(params[:page])
    respond_to do |format|
      format.html 
    end
  end

  def show
    authorize! :read, @geo_ref

    @childs = childs
    @routes = routes
    @topos = @geo_ref.topos.accessible_by(current_ability, :read)
  end

  def sort_childs
    authorize! :update, @geo_ref
    @childs = childs(action: :update)
  end

  def reorder_childs
    authorize! :update, @geo_ref
    priorities = params.require(:priorities)

    childs(action: :update).each do |c|
      next unless priorities.key? c.id.to_s

      c.update!(priority: priorities[c.id.to_s])
    end

    render json: {}
  end

  def sort_routes
    authorize! :update, @geo_ref
    @routes = routes(action: :update)
  end

  def reorder_routes
    authorize! :update, @geo_ref
    priorities = params.require(:priorities)

    routes(action: :update).each do |r|
      next unless priorities.key? r.id.to_s

      r.update!(priority: priorities[r.id.to_s])
    end

    render json: {}
  end

  def new
    @geo_ref = GeoRef.new(params.permit(:type))

    if params.key? :parent_id
      parent = GeoRef.find(params[:parent_id])
      @geo_ref.parent = parent
      @geo_ref.access = parent.access
    end

    authorize! :create, @geo_ref
    render :new
  end

  def edit
    authorize! :update, @geo_ref
  end

  def create
    @geo_ref = GeoRef.new(geo_ref_params)
    authorize! :create, @geo_ref
    
    @geo_ref.copy_parent_effective_permissions if @geo_ref.parent.present?

    respond_to do |format|
      if @geo_ref.save
        format.html { redirect_to geo_ref_path(@geo_ref), notice: _('Geo ref was successfully created.') }
      else
        format.html { render :new }
      end
    end
  end

  def update
    authorize! :update, @geo_ref
    respond_to do |format|
      if @geo_ref.update(geo_ref_params)
        format.html { redirect_to geo_ref_path(@geo_ref), notice: _('Geo ref was successfully updated.') }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    authorize! :destroy, @geo_ref
    @geo_ref.destroy
    respond_to do |format|
      redirect_url = if @geo_ref.parent.present?
                       geo_ref_path(@geo_ref.parent)
                     else
                       geo_refs_path
                     end
      format.html { redirect_to redirect_url, notice: _('Geo ref was successfully destroyed.') }
    end
  end

  def select_items
    authorize! :read, @geo_ref
  end

  def move_items
    authorize! :read, @geo_ref

    new_geo_ref = @move_items_params.new_geo_ref
    @move_items_params.selected_routes.each do |route|
      route.geo_ref = new_geo_ref
      route.skip_geo_ref_update_stats = true
    end
    @move_items_params.selected_geo_refs.each do |geo_ref|
      geo_ref.parent = new_geo_ref
      geo_ref.skip_parent_changed_validation = true
    end

    if @move_items_params.valid?
      authorize! :read, new_geo_ref

      @move_items_params.selected_routes.each do |route|
        authorize! :create, route
        route.save!
      end
      @move_items_params.selected_geo_refs.each do |geo_ref|
        authorize! :create, geo_ref
        geo_ref.save!
      end

      new_geo_ref.update_self_and_parents_stats
      @geo_ref.update_self_and_parents_stats

      new_geo_ref.rebuild_effective_permissions \
        if @move_items_params.selected_geo_refs.any?
    
      redirect_to geo_ref_path(@geo_ref), notice: _('Child items have been moved to new location.')
    else
      select_items
      render :select_items
    end
  end

  private

  def routes(action: :read, order: [:priority, :name])
    @geo_ref.routes.accessible_by(current_ability, action).order(order)
  end

  def childs(action: :read, order: [:priority, :name])
    @geo_ref.childs.accessible_by(current_ability, action).order(order)
  end

  def set_geo_ref
    @geo_ref = GeoRef.find(params[:id])
  end

  def geo_ref_type
    params.require(:geo_ref).permit(:type)
  end

  def geo_ref_params
    p = params.require(:geo_ref).permit(
      :name,
      :type,
      :parent_id,
      :description,
      :body,
      :lat,
      :lng,
      :zone_id,
      :height,
      :orientation,
      :access,
      tag_ids: [],
      alternative_names: []
    )
    p[:alternative_names]&.reject!(&:blank?)
    p
  end

  def geo_ref_move_items_params
    params.fetch(:geo_refs_controller_move_items_params, {}).permit(
      :new_geo_ref_id,
      route_ids: [],
      geo_ref_ids: []
    )
  end

  def set_move_items_params
    @move_items_params = GeoRefsController::MoveItemsParams.new
    @move_items_params.new_geo_ref = GeoRef.find(
      geo_ref_move_items_params[:new_geo_ref_id]
    ) unless geo_ref_move_items_params[:new_geo_ref_id].blank?

    @move_items_params.routes = routes(action: :destroy)
    @move_items_params.selected_routes = routes(action: :destroy) \
      .where(id: geo_ref_move_items_params[:route_ids].to_a.reject(&:blank?))

    @move_items_params.geo_refs = childs(action: :destroy)
    @move_items_params.selected_geo_refs = childs(action: :destroy) \
      .where(id: geo_ref_move_items_params[:geo_ref_ids].to_a.reject(&:blank?))
  end
end

app/views/geo_refs/_access_level_badge.html.erb
<%- if geo_ref.access == 'private' -%>
  <span class="badge badge-danger" data-toggle="tooltip" title="<%= _('Location is private') %> ">
    <i class="fa fa-user-circle"></i>
  </span>
<%- elsif geo_ref.access == 'confidential' -%>
  <span class="badge badge-danger" data-toggle="tooltip" title="<%= _('Location is confidential') %> ">
    <i class="fa fa-user-secret"></i>
  </span>
<%- end -%>

app/views/geo_refs/_head.html.erb
<%= render partial: 'photos/cover_photo', locals: { photo: geo_ref.photos.cover_photos.first } %>

<%- content_for :dropdown do -%>
  <%-
    dropdown_link_options = {
      class: 'dropdown-item',
      icon_class: ['fw']
    }
  -%>
  <% if can?(:update, geo_ref) -%>
    <%= icon_link_to 'edit', _('Edit location'), edit_geo_ref_path(geo_ref), **dropdown_link_options %>
    <%= icon_link_to 'edit', _('Edit child items'), select_items_geo_ref_path(geo_ref), **dropdown_link_options %>
    <div class="dropdown-divider"></div>
  <% end -%>
  <% if can?(:create, Comment.new(target: geo_ref, user: current_user)) -%>
    <%= icon_link_to Comment, _('Add comment'), new_geo_ref_comment_path(geo_ref), **dropdown_link_options %>
  <% end -%>
  <% if can?(:create, GeoRef.new(parent: geo_ref)) -%>
    <%- [
        Country,
        Region,
        Crag,
        Sector,
        Parking
      ].each do |type| -%>
      <%- if type.valid_parent_class?(geo_ref.class) -%>
        <%- label = case
                    when type == Country then _('Add country')
                    when type == Region  then _('Add region')
                    when type == Crag    then _('Add crag')
                    when type == Sector  then _('Add sector')
                    when type == Parking then _('Add parking')
                    end
        -%>
        <%= icon_link_to(
          type,
          label,
          new_geo_refs_path(type: type.to_s, parent_id: geo_ref.id),
          **dropdown_link_options
        ) %>
      <%- end -%>
    <%- end -%>
  <%- end -%>
  <% if geo_ref.is_a?(Crag) && can?(:create, Route.new(geo_ref: geo_ref)) -%>
    <%= icon_link_to Route, _('Add route'), new_route_path(:geo_ref_id => geo_ref.id), **dropdown_link_options %>
  <%- end -%>
  <% if can?(:create, Photo.new(target: geo_ref, user: current_user)) -%>
    <%= icon_link_to Photo, _('Add photo'), new_geo_ref_photo_path(geo_ref), **dropdown_link_options %>
  <% end -%>
  <% if can?(:create, Topo.new(target: geo_ref)) -%>
    <%= icon_link_to Topo, _('Add topo'), new_geo_ref_topo_path(geo_ref), **dropdown_link_options %>
  <% end -%>
  <% if SecondaryZone.valid_geo_ref_type?(geo_ref.class) && can?(:create, SecondaryZone.new(geo_ref: geo_ref)) -%>
    <%= icon_link_to SecondaryZone, _('Add climbing zone'), new_geo_ref_secondary_zone_path(geo_ref), **dropdown_link_options %>
  <% end -%>
  <% if Regulation.valid_geo_ref_type?(geo_ref.class) && can?(:create, Regulation.new(geo_ref: geo_ref)) -%>
    <%= icon_link_to Regulation, _('Add climbing regulation'), new_geo_ref_regulation_path(geo_ref), **dropdown_link_options %>
  <% end -%>
  <% if geo_ref.is_a?(Parking) && can?(:create, Path.new(geo_ref: geo_ref)) -%>
    <%= icon_link_to Path, _('Add path'), new_geo_ref_path_path(geo_ref), **dropdown_link_options %>
  <% end -%>
<% end -%>

<%- content_for :breadcrumb do -%>
  <%= render partial: 'geo_refs/parent_breadcrumb_nav', :locals => { :geo_ref => geo_ref } %>
<%- end -%>

<%- content_for :title_right do -%>
  <% if geo_ref.orientation.present? -%>
    <div class="compass"><div class="compass-pointer" style="transform: rotate(<%= geo_ref.orientation %>deg)"></div></div>
  <% end -%>
  <% if geo_ref.height.present? -%>
    <div class="messure_height"><%= geo_ref.height %>m</div>
  <% end -%>
<% end -%>

<%- content_for :title do -%>
  <%= geo_ref.name %>
  <small><%= _(geo_ref.class.name) %></small>
  <%= render partial: 'geo_refs/access_level_badge', :locals => { :geo_ref => geo_ref } %>
  <%= render partial: 'geo_refs/routes_grade_stats', :locals => { :geo_ref => geo_ref } %>
<%- end -%>

<%- content_for :icon, geo_ref.icon -%>

app/views/geo_refs/_parent_breadcrumb_nav.html.erb
<% include_self ||= false %>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="<%= browse_geo_refs_path %>"><span class="fa fa-globe"></span></a></li>
    <% geo_ref.parents.reverse.each do |parent| -%>
      <li class="breadcrumb-item"><%= link_to parent.name, geo_ref_path(parent) %></li>
    <% end -%>
    <% if include_self -%>
      <li class="breadcrumb-item"><%= link_to geo_ref.name, geo_ref_path(geo_ref) %></li>
    <% end -%>
  </ol>
</nav>

app/views/geo_refs/_primary_tab_nav.html.erb
<%- content_for :tab_nav do -%>
  <%= render_navigation do |primary|
    primary.item :search, _('Search'), geo_refs_path
    primary.item :browse, _('Browse'), browse_geo_refs_path, highlights_on: %r(/geo_refs/(?:\d+|browse)$)
    primary.dom_class = 'nav nav-tabs mb-3'
  end %>
<%- end -%>

app/views/geo_refs/browse.html.erb
<%- content_for :buttons do -%>
  <% if can?(:create, GeoRef) -%>
    <%= link_to "<span class=\"fa fa-plus\"></span> #{_('New Country')}".html_safe, new_geo_refs_path(type: 'Country'), class: 'btn btn-success pull-right' %>
  <% end -%>
<% end -%>

<%- content_for :title, _('Locations') -%>
<%- content_for :icon, GeoRef.icon -%>

<%= render partial: 'geo_refs/primary_tab_nav' %>

<%- content_for :breadcrumb do -%>
  <%= render partial: 'parent_breadcrumb_nav', :locals => { :geo_ref => GeoRef.new } %>
<%- end -%>

<ul class="content-list">
  <% @geo_refs.each do |geo_ref| -%>
    <%= render partial: 'geo_refs/content-list/default', :locals => { :item => geo_ref } %>
  <% end -%>
</ul>

app/views/geo_refs/new.html.erb
<%- content_for :title, _('New %{geo_ref_type}') % { geo_ref_type: _(@geo_ref.type) } -%>
<%- content_for :icon, @geo_ref.icon -%>

<%= render 'form' %>

app/views/geo_refs/show.html.erb
<%= render partial: 'geo_refs/head', :locals => { :geo_ref => @geo_ref } %>
<%= render partial: 'geo_refs/secondary_tab_nav', :locals => { :geo_ref => @geo_ref } %>

<% if @geo_ref.closure.present? -%>
  <div class="alert alert-<%= @geo_ref.closure.active? ? 'danger' : 'info' %>" role="alert">
    <i class="fa fa-lock" aria-hidden="true"></i>
    <%= link_to _('Closure'), @geo_ref.closure, class: 'alert-link' %> from <%= @geo_ref.closure.start_at %> to <%= @geo_ref.closure.end_at %>
    (<%= @geo_ref.closure.kind %>)
  </div>
<% end -%>

<%= render(
  partial: 'zones/icon',
  locals: {
    item: @geo_ref.zone,
    size: '3x'
  }
) if @geo_ref.zone.present? %>
<% @geo_ref.secondary_zones.each do |sr| -%>
  <% if can?(:update, sr) -%>
    <%= render(
      partial: 'zones/icon',
      locals: {
        item: sr.zone,
      }
    ) %>
    <%= sr.description %>
    <%= link_to '<span class="fa fa-pencil"></span>'.html_safe, edit_geo_ref_secondary_zone_path(@geo_ref, sr), class: 'btn btn-link btn-sm' %>
  <% end %>
<% end -%>

<%- if @geo_ref.alternative_names.any? -%>
  <%= _('Other names') %>: <%= @geo_ref.alternative_names.join(', ') %>
<%- end -%>

<%= render partial: 'location_map', :locals => { :geo_ref => @geo_ref } %>

<p><em><%= @geo_ref.description %></em></p>

<%= render partial: 'taggables/tags_by_category', :locals => { :tags => @geo_ref.tags } %>

<% if @geo_ref.body.present? -%>
  <%= markdown(@geo_ref.body) %>

  <hr></hr>
<% end -%>

<% if @childs.present? %>
  <ul class="content-list">
    <li>
      <div class="header"><%= _('Regions') %></div>
      <% if can? :update, @geo_ref -%>
        <a class="btn btn-sm btn-outline-secondary pull-right" href="<%=  sort_childs_geo_ref_path @geo_ref %>">
          <i class="fa fa-arrows-v" aria-hidden="true"></i> <%= _('change order') %>
        </a>
      <% end -%>
    </li>
    <% @childs.each do |c| %>
      <%= render partial: 'geo_refs/content-list/default', :locals => { :item => c } %>
    <% end %>
  </ul>
<% end %>

<% if @routes.present? %>
  <ul class="content-list">
    <li>
      <div class="header"><%= _('Routes') %></div>
      <% if can? :update, @geo_ref -%>
        <a class="btn btn-sm btn-outline-secondary pull-right ml-1" href="<%=  sort_routes_geo_ref_path @geo_ref %>">
          <i class="fa fa-arrows-v" aria-hidden="true"></i> <%= _('change order') %>
        </a>
      <% end -%>
    </li>
    <% @routes.each do |r| %>
      <%= render partial: 'routes/content-list/default', :locals => { :item => r } %>
    <% end %>
  </ul>
<% end %>

<% if @topos.present? %>
  <ul class="content-list">
    <li><div class="header"><%= _('Topos') %></div></li>
    <% @topos.each do |topo| %>
      <%= render partial: 'topos/content-list/default', :locals => { :item => topo } %>
    <% end %>
  </ul>
<% end %>

app/views/geo_refs/sort_childs.html.erb
<%= render partial: 'geo_refs/head', :locals => { :geo_ref => @geo_ref } %>
<%= render partial: 'geo_refs/secondary_tab_nav', :locals => { :geo_ref => @geo_ref } %>

<h3><%= _('Editing child locations order') %></h3>

<p><%= _('Drag routes below to sort them') %>:</p>

<sortable-list
  :initial-list="<%= @childs.to_json only: %i[id name] %>"
  reorder-url="<%= reorder_childs_geo_ref_path(@geo_ref) %>"
  ></sortable-list>

app/views/geo_refs/sort_routes.html.erb
<%= render partial: 'geo_refs/head', :locals => { :geo_ref => @geo_ref } %>
<%= render partial: 'geo_refs/secondary_tab_nav', :locals => { :geo_ref => @geo_ref } %>

<h3><%= _('Editing route order') %></h3>

<p><%= _('Drag routes below to sort them') %>:</p>

<sortable-list
  :initial-list="<%= @routes.to_json only: %i[id name] %>"
  reorder-url="<%= reorder_routes_geo_ref_path(@geo_ref) %>"
  ></sortable-list>